name: Deploy Student App (QA)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend to GCP QA VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.QA_BACKEND_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH_KEY }}
          port: 22

          script: |
            cd /home/propti/gcp-3-tier-deployment

            echo "Pulling latest code..."
            git checkout qa
            git pull origin qa

            echo "Installing packages..."
            npm install

            echo "Restarting Backend..."
            pm2 restart student-app-qa || pm2 start server.js --name student-app-qa

            pm2 save

            echo "Backend Deployment Successful"

      - name: Deploy Frontend to GCP QA VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.QA_FRONTEND_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH_KEY }}
          port: 22

          script: |
            cd /home/propti/gcp-3-tier-deployment

            echo "Pulling latest code..."
            git checkout qa
            git pull origin qa

            echo "Restarting Frontend..."
            pm2 restart frontend-qa

            pm2 save

            echo "Frontend Deployment Successful"
